

export const TYPES = {
    UserService: Symbol.for("UserService"),
    UserProvider: Symbol.for("UserProvider"),
    TransactionService: Symbol.for("TransactionService"),
    TransactionProvider: Symbol.for("TransactionProvider"),
    AccountService: Symbol.for("AccountService"),
    AccountProvider: Symbol.for("AccountProvider"),
    UserController: Symbol.for("UserController"),
    TransactionController: Symbol.for("TransactionController"),
    AccountController: Symbol.for("AccountController"),
    UserRouter: Symbol.for("UserRouter"),
    TransactionRouter: Symbol.for("TransactionRouter"),
}